### PR TITLE
add support for []uint8 slices

### PR DESCRIPTION
**Pull request by martinlindhe**
Hello and thanks for a very useful lib!
We have used it extensively in https://github.com/martinlindhe/wmi_exporter

I am currently implementing support for exporting SMART hdd data (disk health info), and they live in a byte array, so I have implemented support for parsing it in this pr.

I looked everywhere for another WMI class that had a byte array in order to provide a test,
but I couldn't find any.

I have tested this on `MSStorageDriver_ATAPISmartData`, which needs admin rights to access, making testing even more troublesome.

Anyway, here's the code I used

```go
type MSStorageDriver_ATAPISmartData struct {
	InstanceName    string
	Active          bool
	SelfTestStatus  uint64
	TotalTime       uint64
	SmartCapability uint64
	VendorSpecific  []uint8
}

func () grab() {
	var dst []MSStorageDriver_ATAPISmartData
	if err := wmi.QueryNamespace(wmi.CreateQuery(&dst, ""), &dst, `root\wmi`); err != nil {
		return nil, err
	}
}
```

### CODE REVIEW

**Comment by chrisgraf** [comment]
Hi, is there a reason why this pull request was not yet accepted? It would be great if someone could comment on this...

**Comment by mnewswanger** [comment]
I'm looking into this and should have some feedback later this week / early next

**Comment by martinlindhe** [comment]
Thank you, Mike!

**Comment by mnewswanger** [comment]
I'm building and deploying this into out infrastructure this week to do some canary testing for memory leaks (I don't see anything that looks concerning, but we want to make sure our users aren't negatively affected as best we can), and provided things look good there, I'll merge this into master and pull it into scollector as well.

**Comment by mnewswanger** [comment]
Thanks for the contribution @martinlindhe.  This is merged into master and Bosun's scollector.

**Pull request merged**
