### PR TITLE
fixed fetching arrays from wmi object properties

### LINKED ISSUE #42: failed to print string array
I am trying to print the gateway of each NetAdapter by following code,
It print `[]` for all netadapters, not sure if this is a bug.

```
package main

import "github.com/StackExchange/wmi"
import "fmt"

// https://msdn.microsoft.com/en-us/library/aa394217(v=vs.85).aspx
type Win32_NetworkAdapterConfiguration struct {
	IPAddress []string
	DHCPServer string
	MACAddress string
	DefaultIPGateway []string
}

func main() {
	var dst2 []Win32_NetworkAdapterConfiguration
	query := fmt.Sprintf("")
	q := wmi.CreateQuery(&dst2, query)
	err := wmi.Query(q, &dst2)
	if err != nil {
		fmt.Println(err)
	}
	for _, v := range dst2 {
		fmt.Println(v.MACAddress, v.IPAddress, v.DHCPServer, v.DefaultIPGateway)
	}	
}
```

### PR DESCRIPTION
**Pull request by graf0**
fixed #42

### CODE REVIEW

**Comment by graf0** [comment]
But I think that solution by Dmitry Karmazin, #41 is better.

**Comment by captncraig** [comment]
Ok, I merged #41, that should sort it, right?

**Comment by graf0** [comment]
> Ok, I merged #41, that should sort it, right?

Yes, I've just checked example with IPAddress property, which is array - works like charm, thanks! :)

**Comment by troian** [comment]
Guys I'm seeing that panic and looks like it is related to arrays

```
runtime: VirtualAlloc of 68719476736 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x53f9ba, 0xd)
        C:/Go/src/runtime/panic.go:608 +0x79
runtime.sysMap(0xc000400000, 0x1000000000, 0x64bdd8)
        C:/Go/src/runtime/mem_windows.go:122 +0x138
runtime.(*mheap).sysAlloc(0x6330e0, 0x1000000000, 0x3d4fdb0, 0x3d4fd88)
        C:/Go/src/runtime/malloc.go:619 +0x1d9
runtime.(*mheap).grow(0x6330e0, 0x800000, 0x0)
        C:/Go/src/runtime/mheap.go:920 +0x49
runtime.(*mheap).allocSpanLocked(0x6330e0, 0x800000, 0x64bde8, 0x20)
        C:/Go/src/runtime/mheap.go:848 +0x361
runtime.(*mheap).alloc_m(0x6330e0, 0x800000, 0x3d40100, 0x40b3c9)
        C:/Go/src/runtime/mheap.go:692 +0x127
runtime.(*mheap).alloc.func1()
        C:/Go/src/runtime/mheap.go:759 +0x53
runtime.(*mheap).alloc(0x6330e0, 0x800000, 0x3010100, 0x414ef3)
        C:/Go/src/runtime/mheap.go:758 +0x91
runtime.largeAlloc(0x1000000000, 0x440001, 0xc0000902d0)
        C:/Go/src/runtime/malloc.go:1019 +0x9e
runtime.mallocgc.func1()
        C:/Go/src/runtime/malloc.go:914 +0x4d
runtime.systemstack(0x0)
        C:/Go/src/runtime/asm_amd64.s:351 +0x6b
runtime.mstart()
        C:/Go/src/runtime/proc.go:1229

goroutine 4 [running, locked to thread]:
runtime.systemstack_switch()
        C:/Go/src/runtime/asm_amd64.s:311 fp=0xc00006f348 sp=0xc00006f340 pc=0x451080
runtime.mallocgc(0x1000000000, 0x517e40, 0x1, 0x0)
        C:/Go/src/runtime/malloc.go:913 +0x8d5 fp=0xc00006f3e8 sp=0xc00006f348 pc=0x40b985
runtime.makeslice(0x517e40, 0x100000000, 0x100000000, 0x0, 0x0, 0xc00006f490)
        C:/Go/src/runtime/slice.go:70 +0x7e fp=0xc00006f418 sp=0xc00006f3e8 pc=0x43c06e
github.com/go-ole/go-ole.(*SafeArrayConversion).ToValueArray(0xc00006f690, 0x18, 0x50f4a0, 0x55f5e0)
        github.com/go-ole/go-ole/safearrayconversion.go:37 +0x6e fp=0xc00006f500 sp=0xc00006f418 pc=0x4e9cce
github.com/StackExchange/wmi.(*Client).loadEntity(0x62fe50, 0x508960, 0xc00008ee70, 0x37f3058, 0x0, 0x0)
        github.com/StackExchange/wmi/wmi.go:378 +0xf46 fp=0xc00006f7c8 sp=0xc00006f500 pc=0x4efec6
github.com/StackExchange/wmi.(*Client).Query.func1(0xc00006f8c8, 0x55f5e0, 0x521680, 0x62fe50, 0xc00006f968, 0xc00006f958, 0x1, 0xc00006f998, 0x0, 0x0)
       github.com/StackExchange/wmi/wmi.go:215 +0xff fp=0xc00006f858 sp=0xc00006f7c8 pc=0x4f1c2f
github.com/StackExchange/wmi.(*Client).Query(0x62fe50, 0xc0000cc0a0, 0x4a, 0x508020, 0xc0000be060, 0xc0000be0a0, 0x2, 0x2, 0x0, 0x0)
        github.com/StackExchange/wmi/wmi.go:230 +0x828 fp=0xc00006f9c0 sp=0xc00006f858 pc=0x4ee9e8
github.com/StackExchange/wmi.Query(0xc0000cc0a0, 0x4a, 0x508020, 0xc0000be060, 0xc0000be0a0, 0x2, 0x2, 0x10, 0xc0000c20e8)
        github.com/StackExchange/wmi/wmi.go:76 +0x10c fp=0xc00006fa20 sp=0xc00006f9c0 pc=0x4ee18c
github.com/StackExchange/wmi.QueryNamespace(0xc0000cc0a0, 0x4a, 0x508020, 0xc0000be060, 0x542534, 0x16, 0x2, 0x0)
        github.com/StackExchange/wmi/wmi.go:59 +0xdf fp=0xc00006fa90 sp=0xc00006fa20 pc=0x4ee03f
...
```

Here is code
```
type Msvm_GuestNetworkAdapterConfiguration struct {
	InstanceID  string
	IPAddresses []string
}

func main() {
var q string
	var ips []Msvm_GuestNetworkAdapterConfiguration
	q = wmi.CreateQuery(&ips, "")
	if err = wmi.QueryNamespace(q, &ips, `root\virtualization\v2`); err != nil {
		fmt.Println(err.Error())
	}
}
```

**Pull request closed without merging**
