### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by czxcc**
module declares

### CODE REVIEW

**Comment by czxcc** [comment]
module declares

**Comment by lespea** [comment]
Without this pr you can't fetch this package at all with go mod.  Please merge asap.

**Comment by lespea** [comment]
Also since you've adding go.mod you should probably do a new tagged release.

**Comment by tlimoncelli** [comment]
I've added the tag.  Please verify (my git knowledge isn't the greatest :-( )

**Comment by lespea** [comment]
I believe you need to make the tag `v1.2.0`

**Comment by tlimoncelli** [comment]
Done.

**Comment by lespea** [comment]
Did you accidentally tag the wrong commit?  `v1.2.0` is pointing to `fe8f175` but `1.2.0` is pointing to `37ec4cb`.  `fe8f175` was before any of the go.mod stuff was added.  I'm also not 100% but you might need to remove the `1.2.0` tag?  Maybe not but might be confusing having 2 tags for the same version.

**Comment by tlimoncelli** [comment]
Drat. I didn't do a "git pull".

I removed and re-added the v1.2.0 tag.  PTAL

**Comment by lespea** [comment]
Perfect!

```
> go mod verify && go mod tidy
all modules verified
go: downloading github.com/StackExchange/wmi v1.2.0
```

**Pull request merged**
